# Generated by Django 3.2.6 on 2021-08-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('authors', models.CharField(blank=True, max_length=120, null=True)),
                ('published_date', models.IntegerField(blank=True, null=True)),
                ('categories', models.CharField(blank=True, max_length=120, null=True)),
                ('average_rating', models.IntegerField(blank=True, null=True)),
                ('ratings_count', models.IntegerField(blank=True, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
